version: '3.5'
 
services:      
  springapi:
    image: springboot-docker-compose-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: springapi
    volumes:
      - ./data/springboot-docker-compose-app
    ports:
      - "8080:8080"
    networks:
      - backendNetwork
      - frontendNetwork
       
  angular-service:
    image: nginx:alpine
    container_name: angular
    ports: 
      - 4200:80
    depends_on:
      - springapi
    ports: 
      - "4200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./recipe/dist/recipe/:/usr/share/nginx/html
    networks:
      - frontendNetwork

networks:
  backendNetwork:
  frontendNetwork: